"""Pydantic models for the job search automation workflow."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ── CV Profile ──────────────────────────────────────────────────────────────


class Experience(BaseModel):
    """A single work experience entry."""

    title: str = Field(description="Job title")
    company: str = Field(description="Company name")
    duration: str = Field(description="Duration e.g. 'Jan 2022 - Present'")
    description: str = Field(default="", description="Role description / highlights")


class Education(BaseModel):
    """A single education entry."""

    degree: str = Field(description="Degree name")
    institution: str = Field(description="University / College name")
    year: str = Field(default="", description="Graduation year or period")


class CVProfile(BaseModel):
    """Structured profile extracted from a CV by the AI agent."""

    name: str = Field(default="", description="Candidate full name")
    email: str = Field(default="", description="Candidate email")
    phone: str = Field(default="", description="Candidate phone number")
    location: str = Field(default="", description="Current location / city")
    summary: str = Field(default="", description="Professional summary")
    skills: list[str] = Field(default_factory=list, description="Technical & soft skills")
    experience: list[Experience] = Field(
        default_factory=list, description="Work experience entries"
    )
    education: list[Education] = Field(
        default_factory=list, description="Education entries"
    )
    preferred_roles: list[str] = Field(
        default_factory=list,
        description="Roles the candidate is best suited for based on experience",
    )
    years_of_experience: float = Field(
        default=0, description="Total years of professional experience"
    )


# ── Job Listing ─────────────────────────────────────────────────────────────


class HRContact(BaseModel):
    """A recruiter / HR contact discovered for a job listing."""

    name: str = Field(default="Hiring Manager", description="Contact name")
    email: str = Field(description="Contact email")
    source: str = Field(
        default="inferred",
        description="How the email was found: 'extracted', 'inferred', 'pattern'",
    )


class JobListing(BaseModel):
    """A single job listing found during search."""

    title: str = Field(description="Job title")
    company: str = Field(description="Company name")
    location: str = Field(default="", description="Job location")
    url: str = Field(description="Job posting URL")
    source: str = Field(
        default="google", description="Portal source: naukri, indeed, linkedin, google"
    )
    description_snippet: str = Field(
        default="", description="Short description or snippet"
    )
    posted_date: str = Field(default="", description="When the job was posted")
    hr_contacts: list[HRContact] = Field(
        default_factory=list, description="Discovered HR/recruiter contacts"
    )


# ── Email ────────────────────────────────────────────────────────────────────


class EmailStatus(str, Enum):
    """Status of a draft email."""

    PENDING_REVIEW = "pending_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    SENT = "sent"
    FAILED = "failed"


class DraftEmail(BaseModel):
    """A personalized email draft generated by the AI agent."""

    id: str = Field(description="Unique email draft ID")
    to_email: str = Field(description="Recipient email")
    to_name: str = Field(default="Hiring Manager", description="Recipient name")
    subject: str = Field(description="Email subject line")
    body_html: str = Field(description="HTML email body")
    body_text: str = Field(description="Plain text email body")
    job_title: str = Field(default="", description="Related job title")
    company: str = Field(default="", description="Related company")
    job_url: str = Field(default="", description="Related job URL")
    status: EmailStatus = Field(default=EmailStatus.PENDING_REVIEW)
    created_at: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="When the draft was created",
    )


class SendResult(BaseModel):
    """Result of an email send attempt."""

    email_id: str = Field(description="Draft email ID")
    success: bool = Field(description="Whether the send succeeded")
    message_id: str = Field(default="", description="SMTP message ID if successful")
    error: str = Field(default="", description="Error message if failed")


# ── Workflow Run ─────────────────────────────────────────────────────────────


class WorkflowStep(str, Enum):
    """Current step in the workflow pipeline."""

    IDLE = "idle"
    ANALYZING_CV = "analyzing_cv"
    SEARCHING_JOBS = "searching_jobs"
    EXTRACTING_CONTACTS = "extracting_contacts"
    GENERATING_EMAILS = "generating_emails"
    AWAITING_REVIEW = "awaiting_review"
    SENDING_EMAILS = "sending_emails"
    COMPLETED = "completed"
    FAILED = "failed"


class WorkflowRun(BaseModel):
    """A complete workflow run record."""

    run_id: str = Field(description="Unique run identifier")
    cv_filename: str = Field(default="", description="Uploaded CV filename")
    current_step: WorkflowStep = Field(default=WorkflowStep.IDLE)
    cv_profile: Optional[CVProfile] = None
    job_listings: list[JobListing] = Field(default_factory=list)
    draft_emails: list[DraftEmail] = Field(default_factory=list)
    sent_results: list[SendResult] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
    created_at: str = Field(
        default_factory=lambda: datetime.now().isoformat()
    )


# ── Job Auto-Apply Models ────────────────────────────────────────────────────


class JobApplyPreferences(BaseModel):
    """User preferences for auto-applying to jobs."""

    expected_salary: str = Field(default="", description="Expected salary range")
    current_ctc: str = Field(default="", description="Current CTC / salary")
    expected_ctc: str = Field(default="", description="Expected CTC / salary")
    notice_period: str = Field(default="Immediate", description="Notice period")
    work_authorization: str = Field(default="", description="Work authorization status")
    willing_to_relocate: bool = Field(default=False, description="Willing to relocate")
    preferred_job_titles: list[str] = Field(default_factory=list, description="Desired job titles")
    preferred_locations: list[str] = Field(default_factory=list, description="Preferred cities")
    years_of_experience: float = Field(default=0, description="Total years of experience")
    additional_info: dict = Field(
        default_factory=dict,
        description="Extra key-value pairs for custom application questions",
    )


class JobSearchCriteria(BaseModel):
    """Search parameters for finding jobs on LinkedIn."""

    keywords: str = Field(..., description="Job search keywords / title")
    location: str = Field(default="", description="City or region")
    experience_level: str = Field(default="", description="Entry, Associate, Mid-Senior, Director")
    date_posted: str = Field(default="", description="Past 24h, Past Week, Past Month, Any")
    easy_apply_only: bool = Field(default=True, description="Filter to Easy Apply jobs only")


class JobApplyRequest(BaseModel):
    """Request body for starting an auto-apply session."""

    profile_id: str = Field(..., description="ID of the saved profile")
    criteria: JobSearchCriteria
    max_applications: int = Field(default=10, ge=1, le=50)


class ApplicationResult(BaseModel):
    """Result of a single job application attempt."""

    id: str = Field(default="")
    job_title: str = Field(default="")
    company: str = Field(default="")
    job_url: str = Field(default="")
    job_location: str = Field(default="")
    apply_type: str = Field(default="unknown")
    status: str = Field(default="pending")
    questions_answered: dict = Field(default_factory=dict)
    error_message: str = Field(default="")


class JobApplySessionStatus(BaseModel):
    """Status response for a running or completed auto-apply session."""

    session_id: str
    status: str
    max_applications: int = 0
    applied_count: int = 0
    skipped_count: int = 0
    failed_count: int = 0
    applications: list[ApplicationResult] = Field(default_factory=list)
    created_at: str = ""
